service: s3-facealignment


provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-south-1
  timeout: 60
  environment: 
    S3_BUCKET: eva4p2-s3-anilbhatt1
    MODEL_PATH: shape_predictor_5_face_landmarks.dat
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:getObject
      Resource: arn:aws:s3:::eva4p2-s3-anilbhatt1/*

custom:
  pythonRequirements:
    dockerizePip: true
    zip: true
    slim: true
    strip: false
    noDeploy:
      - docutils
      - jmespath
      - pip
      - python-dateutil
      - setuptools
      - six
      - tensorboard
    useStaticCache: true
    useDownloadCache: true
    cacheLocation: "./cache"

package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**
    - cache/**
    - test/**
    - __pycache__/**
    - .pytest_cache/**
    - model/**

functions:
  classify_image:
    handler: face_alignment_handler
    memorySize: 3008
    timeout: 60
    events:
      - http:
         path: classify-path
         method: post
         cors: true      

plugins:
  - serverless-python-requirements
